-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgR8n+mD+vwNLSvW5RsNL3RxM9AqTJnCXSwXMlBTiabpWgCgYIKoZIzj0DAQehRANCAAQTr/GL2f9uqaiAiMPnBulUFf3QquIyHWwp5T5fvl0jDqGASgIa5ZYxEdjKIQhNsohu+S8fV4SuvjB1v5UgMeOe
-----END PRIVATE KEY-----